Algoritmo "Salário do funcionário"
// Disciplina: Algoritmo
// Professor: Gustavo Guanabara
// Autor(a): João Pedro
// Data atual: 21/02/2026

Var

   nomeFuncionario: caractere
   salario: real

Inicio

     escreva("Qual é o seu nome? ")
     leia(nomeFuncionario)
     escreva("Qual é o seu salário? ")
     leia(salario)
     escrevaL("")
     
     escreva("O funcionário ", nomeFuncionario," tem um salário de R$ ", salario, " em Junho.")

Fimalgoritmo