Algoritmo "Soma de dois números"
// Disciplina: Algoritmo
// Professor: Gustavo Guanabara
// Autor(a): João Pedro
// Data atual: 21/02/2026

Var

   numero1, numero2, soma: inteiro

Inicio

     escreva("Digite um número: ")
     leia(numero1)
     escreva("Digite outro número: ")
     leia(numero2)

     soma <- numero1 + numero2
     
     escreva("A soma entre ", numero1," e o ", numero2," será igual a ", soma)

Fimalgoritmo