Algoritmo "Antecessor e Sucessor"
// Disciplina: Algoritmo
// Professor: Gustavo Guanabara
// Autor(a): João Pedro
// Data atual: 21/02/2026

Var

   numero, antecessor, sucessor: real
   
Inicio

     escreva("Digite um número: ")
     leia(numero)
     
     antecessor <- numero - 1
     sucessor <- numero + 1
     
     escreval("O antecessor é ", antecessor, ".")
     escreva("O sucessor é ", sucessor, ".")

Fimalgoritmo