Algoritmo "O dobro e terça parte"
// Disciplina: Algoritmo
// Professor: Gustavo Guanabara
// Autor(a): João Pedro
// Data atual: 23/02/2026

Var

   numero, dobro, tercaParte:real

Inicio

      escreva("Digite um número: ")
      leia(numero)
      
      dobro <- numero * 2
      tercaParte <- numero / 3

      escreval("O dobro de ", numero, " será: ", dobro)
      escreva("E a terça parte de ", numero, " será: ", tercaParte)

Fimalgoritmo